### ISSUE TITLE
Update old elasticsearch version

### ISSUE THREAD

**Issue by martinjobb** [Frojd/Frojd-Bedrock#21]
In docker-compose.yml elasticsearch:2.4 is specified, but Elasticpress recomends 5.0+. Would it be ok to update to 5.6.10?

**Comment by mikaelengstrom** [comment]
IDK. I think the version of development services should follow whatever version is installed on production server. For ubuntu LTS 16.04 that means elastic v2.

However we could for sure bump the version to whatever is bundled with ubuntu 18.04.
