### ISSUE TITLE
Add basic acf-settings

### ISSUE THREAD

**Issue by saraojelind** [Frojd/Frojd-Bedrock#7]
Add a theme settings page in admin with basic fields:
- 404 - title and description
- Footer - Link list, follow links, contact
- Cookie popup - Text
- Browser support popup - Text

**Comment by mikaelengstrom** [comment]
I have omitted the footer-stuff for now. Lets discuss that later.

**Comment by mikaelengstrom** [comment]
wysiwyg + linklist

**Comment by mikaelengstrom** [comment]
tabse
